version: '3.8'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=prescription
      - POSTGRES_PASSWORD=prescription
      - POSTGRES_DB=prescription

  api:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://prescription:prescription@db:5432/prescription
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
